/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3e2b4338-299f-4ce1-8e38-c7514fb58a07",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1H3phOiUI",
    "aws_user_pools_web_client_id": "50i73pu4cr3okmf8lm9q5cpb5k",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "suiaapi",
            "endpoint": "https://o6ebr9ta03.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
